### ISSUE TITLE
Intel Specific Dependencies

### ISSUE THREAD

**Issue by martinvahi** [The-OpenROAD-Project/RePlAce#2]
A cite from the README.md

> Pre-requisite
> Intel MKL and IPP package

Part of the context of the flaw might be the various new ARM based clusters like the 
http://exanode.eu/
and the various other options, including the [LEON](https://en.wikipedia.org/wiki/LEON) and the [RISC-V](https://riscv.org/).

**Comment by xobs** [comment]
Similarly, I'm having trouble downloading those packages from Intel.  I'm stuck in a loop where I click "Download", and they send me to a page that includes a "Download" link that takes me to a page that sends me an email that includes a link..

**Comment by mgwoo** [comment]
Solved and close.
