### ISSUE TITLE
RePlAce fails to place all Insts on grid for Coyote

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/RePlAce#44]
After running RePlAce on Coyote and loading into innovus, checkplace reports several cells not placed on the manufacturing grid
## Insts not on placement grid, or blocks not on manufacturing grid (279) ##

See attachment: t9_place_2019-06-04_10-19.tar.gz

**Comment by mgwoo** [comment]
Hi Tutu,
I was not able to find your archive file...
Could you send this file to my email?

Kind regards,
Mingyu Woo

**Comment by tajayi** [comment]
Did you find it now?

**Comment by mgwoo** [comment]
Yes. I've found out. Let me check this issue.

**Comment by mgwoo** [comment]
NTUPlace* will be removed and OpenDP will be used.
Close this issue.
