### ISSUE TITLE
OpenDP invalidates physical-only instances

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/RePlAce#47]
I noticed innovus reporting a reduced cell count when comparing the results. I then noticed the following warning when loading the def
```
**WARN: (IMPDF-200):	Instance ENDCAP_CORE_20 is not found in db and ignored.
If this is a physical-only instance, it should have '+ SOURCE DIST' attribute.
```
Comparing the input lef to the output lef, i noticed that ` + SOURCE DIST` was missing from the output of OpenDP.

**Comment by mgwoo** [comment]
I've fixed this bug in the following commit: 
https://github.com/sanggido/OpenDP/commit/501f0c803a8d61cb6585e0e91662bfcad1edba42

Could you check this again?
