### ISSUE TITLE
RePlace crashes while placing ISPD06 circuits

### ISSUE THREAD

**Issue by jucemarmonteiro** [The-OpenROAD-Project/RePlAce#51]
RePLace crashes while placing ISPD06 circuits.
The placer requires routing data which is not available in the 2006 ISPD circuits.
    **ERROR: RouteInst failed to get LAYER information from LEF**

Please find the log as follows.

$ ./replace -bmflag ispd -aux adaptec1/adaptec1.aux -onlyGP -output placement -den 0.7    
CMD :  ./replace -bmflag ispd -aux adaptec1/adaptec1.aux -onlyGP -output placement -den 0.7 
INFO:  VERSION, Compiled at Aug 11 2019 09:40:45
INFO:  Now is Sun Aug 11 10:35:36 2019

** WARNING: Your Detail Placement Step must be skipped.
              (i.e. this program will be executed as -onlyGP)
     If you want to have DP after GP, please specify -dpflag and -dploc.

INFO:  Target Density = 0.700000
INFO:  Experiment Index 2
INFO:  DIR_PATH = placement/ispd/adaptec1/experiment002

PROC:  BEGIN IMPORTING PLACEMENT INPUT
INFO:  PLACEMENT INSTANCES INCLUDING STDCELL and MOVABLE MACRO
INFO:    Instance   MinX=3.00, MaxX=77.00
INFO:               MinY=12.00, MaxY=12.00
INFO:               AvgX=14.73, AvgY=12.00
INFO:      Smallest Instance      o39274  Size 36.00
INFO:      Largest  Instance      o39112  Size 924.00
INFO:  TERMINALS INCLUDING PAD and FIXED MACRO
INFO:    Terminal   MinX=72.00, MaxX=2304.00
INFO:               MinY=24.00, MaxY=2856.00
INFO:               AvgX=278.62, AvgY=436.29
INFO:  #NET=221142
INFO:  #PIN=944053
INFO:    Maximum Net Degree is 2271
INFO:  ASPECT RATIO=0.998878
INFO:  ROW = (MinX=459.000000, MinY=459.000000)
INFO:  ROW = (MaxX=11151.000000, MaxY=11139.000000)
INFO:  TERM: (22.000000, 22.000000) - (11589.000000, 11589.000000)
INFO:  NOTE:   0% Whitespace is Added to Each Tier.
INFO:    LARGEST MACRO SIZE (X,Y) = (77, 12)
INFO:    TIER DIMENSION (X,Y) = (10692, 10680)
INFO:  #STDCELL=210904,  #movableMACRO=0,  #fixedMACRO=543
INFO:  #ROW=890,  ROW HEIGHT=12, TIER DEPTH=1
INFO:  GLOBAL.SPACE.MIN = (22.000000, 22.000000)
INFO:  GLOBAL.SPACE.MAX = (11589.000000, 11589.000000)
INFO:  PLACE.ORIGIN = (459, 459)
INFO:  PLACE.END = (11151, 11139)

PROC:  END IMPORTING PLACEMENT INPUT

PROC:  BEGIN INITIAL PLACEMENT (IP)
PROC:  Conjugate Gradient (CG) method to obtain the IP
INFO:  The Initial HPWL is 47895080.000000
INFO:  The Matrix Size is 210904
INFO:  IP  0,  CG Error 0.000366,  HPWL 46455352.000000,  CPUtime 1.84
INFO:  IP  1,  CG Error 0.000236,  HPWL 45368104.000000,  CPUtime 1.90
INFO:  IP  2,  CG Error 0.000115,  HPWL 44386312.000000,  CPUtime 1.81
INFO:  IP  3,  CG Error 0.000118,  HPWL 43533904.000000,  CPUtime 1.83
INFO:  IP  4,  CG Error 0.000079,  HPWL 42995104.000000,  CPUtime 1.84
INFO:  IP  5,  CG Error 0.000045,  HPWL 42599216.000000,  CPUtime 1.83
INFO:  IP  6,  CG Error 0.000037,  HPWL 42372400.000000,  CPUtime 1.79
INFO:  IP  7,  CG Error 0.000034,  HPWL 42159832.000000,  CPUtime 1.80
INFO:  IP  8,  CG Error 0.000029,  HPWL 42043056.000000,  CPUtime 1.78
INFO:  IP  9,  CG Error 0.000024,  HPWL 41911872.000000,  CPUtime 1.82
INFO:  IP 10,  CG Error 0.000022,  HPWL 41841832.000000,  CPUtime 1.81
INFO:  IP 11,  CG Error 0.000020,  HPWL 41742176.000000,  CPUtime 1.79
INFO:  IP 12,  CG Error 0.000019,  HPWL 41709708.000000,  CPUtime 1.86
INFO:  IP 13,  CG Error 0.000019,  HPWL 41644000.000000,  CPUtime 1.87
INFO:  IP 14,  CG Error 0.000016,  HPWL 41638240.000000,  CPUtime 1.82
INFO:  IP 15,  CG Error 0.000014,  HPWL 41597052.000000,  CPUtime 1.79
INFO:  IP 16,  CG Error 0.000014,  HPWL 41604900.000000,  CPUtime 1.88
INFO:  IP 17,  CG Error 0.000013,  HPWL 41571488.000000,  CPUtime 1.92
INFO:  IP 18,  CG Error 0.000013,  HPWL 41580864.000000,  CPUtime 1.89
INFO:  IP 19,  CG Error 0.000013,  HPWL 41551400.000000,  CPUtime 1.86
INFO:  IP 20,  CG Error 0.000012,  HPWL 41561672.000000,  CPUtime 1.84
INFO:  IP 21,  CG Error 0.000011,  HPWL 41535172.000000,  CPUtime 1.80
INFO:  IP 22,  CG Error 0.000011,  HPWL 41547376.000000,  CPUtime 1.80
INFO:  IP 23,  CG Error 0.000011,  HPWL 41522168.000000,  CPUtime 1.83
INFO:  IP 24,  CG Error 0.000011,  HPWL 41533984.000000,  CPUtime 1.87
INFO:  IP 25,  CG Error 0.000011,  HPWL 41510464.000000,  CPUtime 1.82
INFO:  IP 26,  CG Error 0.000010,  HPWL 41523896.000000,  CPUtime 1.84
INFO:  IP 27,  CG Error 0.000012,  HPWL 41499152.000000,  CPUtime 2.22
INFO:  IP 28,  CG Error 0.000012,  HPWL 41510872.000000,  CPUtime 2.26
INFO:  IP 29,  CG Error 0.000013,  HPWL 41487712.000000,  CPUtime 2.05
RESULT:
   HPWL(IP): 110794560.0000 (55961432.0000, 54833124.0000)

PROC:  END INITIAL PLACEMENT (IP)

INFO:  Chip Area: 10692 x 10680 = 114190560 
INFO:  Total_PL_Area = 114190560, %100.00 of chip
INFO:  Total_TermPL_Area = 49164072, %43.05 of PL
INFO:  Total_WS_Area = 65026488, %56.95 of PL
INFO:  Total_Macro_Area = 0, %0.00 of WS
INFO:  Total_StdCell_Area = 37286292, %57.34 of WS
INFO:  Average 80pct Cell Area = 173.3035
INFO:  FillerCell's Area = 173.303467
gFillerCount: 47502
filler_area: 173.303
total_filler_area: : 8.23225e+06
INFO:  FillerCell's X = 14.441956 , FillerCell's Y = 12.000000
INFO:  #CELL = 258406 =  210904 (#MODULE) + 47502 (#FILLER)
INFO:  Average Module Width = 14.732727, Row Height = 12.000000
INFO:  D_MSH = 1024 
INFO:  MSH(X, Y) = (32, 32)
PROC:  Standard Cell 2D Global Placement (cGP2D)
INFO:  Tier 0, Density is 0.326527
tier->modu_cnt:210904
gfiller_cnt: 47502
INFO: (tier 0) area: 114190560
INFO: (tier 0) virt_area: 0
INFO: (tier 0) term_area: 49164072
INFO: (tier 0) modu_area: 37286292
INFO: (tier 0) filler_area: 8232248
min_idx: 210904
max_idx: 258406
gcell_cnt: 258406
tier->filler_cnt: 47502
INFO:  dim_bin_cGP2D.(x,y) = (512, 512)
tier->pmin: (459 459)
**ERROR: RouteInst failed to get LAYER information from LEF**

**Comment by mgwoo** [comment]
Hi jucemarmonteiro,

Could you check https://github.com/The-OpenROAD-Project/RePlAce/issues/41 ? 
Bookshelf will not be supported anymore.

Thanks
