### ISSUE TITLE
Hello! Can you tell me how to generate the visualized image of .def?

### ISSUE THREAD

**Issue by Flians** [The-OpenROAD-Project/RePlAce#59]
Hello!
I noticed the visualized sample in your README.md.
Can you tell me how to generate the visualized image of .def? 
Thank you!

**Comment by mgwoo** [comment]
You can extract an image from RePlAce on the standalone mode. Please read the Tcl usage readme in the following link. 
https://github.com/The-OpenROAD-Project/RePlAce/blob/master/doc/TclCommands.md

**Comment by Flians** [comment]
I got it. Thank you.
